// apps/shell/src/features/LibraryPanel.tsx
import { CATALOG } from '../data/catalog';
import type { SavedStructure } from '../data/library';
import type { SourceFile } from '@biotool/core/domain/types';
import { Icon } from '../ui/Icon';

interface LibraryPanelProps {
  saved: SavedStructure[];
  currentId?: string;
  open: boolean;
  onLoad: (id: string) => void;
  onLoadSaved: (source: SourceFile) => void;
  onRemove: (id: string) => void;
  onImport: () => void;
  onClear: () => void;
  notice: ReactNode;
}

export function LibraryPanel({ saved, currentId, open, onLoad, onLoadSaved, onRemove, onImport, onClear, notice }: LibraryPanelProps) {
  const savedIds = new Set(saved.map((item) => item.source.id));
  const additional = saved.filter((item) => !CATALOG.some((entry) => entry.id === item.source.id));
  return <aside className="library-panel" id="library-panel" data-open={open} data-framework="react-recovery" aria-labelledby="library-heading" tabIndex={0}>
    <div className="library-heading"><h2 id="library-heading">Library</h2><span className="count-label">{saved.length} saved</span></div>
    {notice}
    <p className="library-intro">A few small structures.<br />A lot to discover.</p>
    <h3 className="small-heading">The collection</h3>
    <ul className="library-list">{CATALOG.map((item) => <li key={item.id}>
      <button className="library-item" aria-current={currentId === item.id ? 'true' : undefined}
        onClick={() => onLoad(item.id)}>
        <span className="accession">{item.id}</span>
        <span className="library-item-name">{item.name}<small>{item.topic}</small></span>
        <span className={`availability ${savedIds.has(item.id) ? 'is-saved' : ''}`}
          aria-label={savedIds.has(item.id) ? 'Saved on this device' : item.id === '1CRN' ? 'Bundled example' : 'Not downloaded'} />
      </button>
    </li>)}</ul>
    {additional.length > 0 && <><h3 className="small-heading">Your structures</h3>
      <ul className="library-list saved-list">{additional.map(({ source, residueCount }) => <li key={source.id}>
        <button className="library-item" aria-current={currentId === source.id ? 'true' : undefined} onClick={() => onLoadSaved(source)}>
          <Icon name="folder" /><span className="library-item-name">{source.origin === 'local' ? source.filename : source.id}
            <small>{residueCount.toLocaleString()} observed residues</small></span>
        </button>
        <button className="icon-button" onClick={() => onRemove(source.id)} aria-label={`Remove ${source.filename} from device library`}><Icon name="trash" size={15} /></button>
      </li>)}</ul></>}
    <button className="button import-button" onClick={onImport}><Icon name="upload" /> Open a local file</button>
    <p className="file-hint">PDB, mmCIF, BinaryCIF<br />Local files stay on this device.</p>
    <div className="library-footer"><p>Saved structures work offline once the app is ready for offline use.</p>
      <button className="text-button" onClick={onClear}>Clear saved files</button>
      <a href="https://www.rcsb.org/" target="_blank" rel="noreferrer">RCSB Protein Data Bank <span aria-hidden="true">↗</span></a>
    </div>
  </aside>;
}
import type { ReactNode } from 'react';

// apps/structure-library/src/LibraryPanel.vue
<script setup lang="ts">
import { computed } from 'vue';
import type { LibraryHost, LibrarySnapshot } from '@biotool/contracts';
import LibraryIcon from './LibraryIcon.vue';

const props = defineProps<{
  snapshot: LibrarySnapshot;
  host: LibraryHost;
  idPrefix: string;
}>();

const savedIds = computed(() => new Set(props.snapshot.saved.map((item) => item.id)));
const additional = computed(() => {
  const catalogIds = new Set(props.snapshot.catalog.map((item) => item.id));
  return props.snapshot.saved.filter((item) => !catalogIds.has(item.id));
});
</script>

<template>
  <aside :id="`${idPrefix}-panel`" class="library-panel" :data-open="snapshot.panelOpen"
    data-framework="vue" :aria-labelledby="`${idPrefix}-heading`" tabindex="0">
    <div class="library-heading">
      <h2 :id="`${idPrefix}-heading`">Library</h2>
      <span class="count-label">{{ snapshot.saved.length }} saved</span>
    </div>
    <p class="library-intro">A few small structures.<br />A lot to discover.</p>
    <h3 class="small-heading">The collection</h3>
    <ul class="library-list">
      <li v-for="item in snapshot.catalog" :key="item.id">
        <button type="button" class="library-item" :aria-current="snapshot.currentId === item.id ? 'true' : undefined"
          @click="host.openPublic(item.id)">
          <span class="accession">{{ item.id }}</span>
          <span class="library-item-name">{{ item.name }}<small>{{ item.topic }}</small></span>
          <span class="availability" :class="{ 'is-saved': savedIds.has(item.id) }" role="img"
            :aria-label="savedIds.has(item.id) ? 'Saved on this device' : item.id === '1CRN' ? 'Bundled example' : 'Not downloaded'" />
        </button>
      </li>
    </ul>
    <template v-if="additional.length > 0">
      <h3 class="small-heading">Your structures</h3>
      <ul class="library-list saved-list">
        <li v-for="item in additional" :key="item.id">
          <button type="button" class="library-item" :aria-current="snapshot.currentId === item.id ? 'true' : undefined"
            @click="host.openSaved(item.id)">
            <LibraryIcon name="folder" />
            <span class="library-item-name">{{ item.label }}<small>{{ item.residueCount.toLocaleString() }} observed residues</small></span>
          </button>
          <button type="button" class="icon-button" :aria-label="`Remove ${item.filename} from device library`"
            @click="host.removeSaved(item.id)"><LibraryIcon name="trash" :size="15" /></button>
        </li>
      </ul>
    </template>
    <button type="button" class="button import-button" @click="host.requestImport()">
      <LibraryIcon name="upload" /> Open a local file
    </button>
    <p class="file-hint">PDB, mmCIF, BinaryCIF<br />Local files stay on this device.</p>
    <div class="library-footer">
      <p>Saved structures work offline once the app is ready for offline use.</p>
      <button type="button" class="text-button" @click="host.clearSaved()">Clear saved files</button>
      <a href="https://www.rcsb.org/" target="_blank" rel="noreferrer">RCSB Protein Data Bank <span aria-hidden="true">↗</span></a>
    </div>
  </aside>
</template>
